POST {{baseUrl}}/author/create
Content-Type: application/json

{
  "firstName": "Lebus",
  "lastName": "237",
  "email": "lebus237@yahoo.com",
  "profileImageUrl": "https://jaqtlievrad7l14s.public.blob.vercel-storage.com/default-images/download-%281%29.jpg",
  "biography": "RAS, but lack of concentration",
  "type": "PUBLISHER"
}

###
DELETE {{baseUrl}}/author/ec46b470-f8ea-4f50-bc0d-08c4d46f6630/delete
Content-Type: application/json

###
PATCH {{baseUrl}}/author/ec46b470-f8ea-4f50-bc0d-08c4d46f6630/update
Content-Type: application/json

{
  "firstName": "To DELETE",
  "lastName": "DELETE",
  "email": "delete@yahoo.com",
  "profileImageUrl": "https://jaqtlievrad7l14s.public.blob.vercel-storage.com/default-images/download-%281%29.jpg",
  "biography": "RAS, but lack of concentration",
  "type": "PUBLISHER"
}


###
GET {{baseUrl}}/author/ec46b470-f8ea-4f50-bc0d-08c4d46f6630
Accept: application/json

###
GET {{baseUrl}}/author/collection
Accept: application/json

###
