POST {{baseUrl}}/author/create
Content-Type: application/json

{
  "firstName": "H.G",
  "lastName": "Wells",
  "email": "null@null.com",
  "profileImageUrl": "https://jaqtlievrad7l14s.public.blob.vercel-storage.com/profile-images/H.G._Wells_by_Beresford.jpg",
  "biography": "Né à Atlas House, au 47 High Street dans la ville de Bromley, située une dizaine de kilomètres au sud-est de Londres, Herbert George Wells, Bertie pour sa famille[2], est le quatrième et dernier enfant de Joseph Wells, un jardinier devenu joueur de cricket professionnel et commerçant, et de Sarah Neal, une ancienne domestique[3]. Un héritage permet à la famille de racheter un magasin de porcelaines et d'articles de sport dont elle tire un maigre revenu, complété par les cachets de joueur de cricket de Joseph Wells pour le Kent County Cricket Club[4]",
  "type": "AUTHOR"
}

###
DELETE {{baseUrl}}/author/ec46b470-f8ea-4f50-bc0d-08c4d46f6630/delete
Content-Type: application/json

###
PATCH {{baseUrl}}/author/ec46b470-f8ea-4f50-bc0d-08c4d46f6630/update
Content-Type: application/json

{
  "firstName": "H.G",
  "lastName": "Wells",
  "email": "null@null.com",
  "profileImageUrl": "https://jaqtlievrad7l14s.public.blob.vercel-storage.com/profile-images/H.G._Wells_by_Beresford.jpg",
  "biography": "Né à Atlas House, au 47 High Street dans la ville de Bromley, située une dizaine de kilomètres au sud-est de Londres, Herbert George Wells, Bertie pour sa famille[2], est le quatrième et dernier enfant de Joseph Wells, un jardinier devenu joueur de cricket professionnel et commerçant, et de Sarah Neal, une ancienne domestique[3]. Un héritage permet à la famille de racheter un magasin de porcelaines et d'articles de sport dont elle tire un maigre revenu, complété par les cachets de joueur de cricket de Joseph Wells pour le Kent County Cricket Club[4]",
  "type": "AUTHOR"
}


###
GET {{baseUrl}}/author/c8dddf1c-786a-4656-8fad-d4ad6840e077
Accept: application/json

###
GET {{baseUrl}}/author/collection
Accept: application/json

###
